### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by wang4386** [UCPr251/zzzAuto#1]
在拾取完零号业绩后无法点击确认弹窗
使用的是exe版本

**Comment by UCPr251** [comment]
屏幕分辨率多少
确认框的坐标发我一下，左上角和右下角或者直接全屏截图发我看看

**Comment by wang4386** [comment]
![PixPin_2024-07-27_12-37-04](https://github.com/user-attachments/assets/a08a8fdd-bf0f-498e-be4a-bb2c6ca297c8)
![PixPin_2024-07-27_12-35-27](https://github.com/user-attachments/assets/548a7ce1-d5b0-4257-a08a-7fffc8f538e5)
视频的话看最后一段报错就可以
https://disk.0v7.cn/s/l5i5

**Comment by UCPr251** [comment]
已修复，请尝试最新版[v1.2.2](https://github.com/UCPr251/zzzAuto/releases/tag/v1.2.2)

**Comment by wang4386** [comment]
新版本完美运行，赞
