### ISSUE TITLE
问题：银行

### ISSUE THREAD

**Issue by EmpCCC** [UCPr251/zzzAuto#10]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[Gitee](https://gitee.com/UCPr251/zzzAuto/issues) [Github](https://github.com/UCPr251/zzzAuto/issues)并未发现相同问题

### 你所遇见的问题？

在银行存款获得奖励如果遇上集卡奖励 进阶卡 ，导致脚本停止
![QQ20240820-204114](https://github.com/user-attachments/assets/ab6c6fc9-2425-40cb-9aa3-a6378d089e5a)

### 出现频率

偶尔出现

### 录屏链接

1

### 使用的版本？

v1.6.2

### 控制面板截图

![QQ20240820-204558](https://github.com/user-attachments/assets/a442d861-25d1-4793-862a-0cea71eb2206)

### 屏幕的分辨率？

1920*1080

### 是否开启HDR？

否

### 其他说明

另能不能做个只存款模式

**Comment by UCPr251** [comment]
目前如果刷取过程中遇见了额外集齐四铭徽会交给retry函数来做异常处理，能直接退出副本重试的。
集齐四铭徽的概率还是很小的，如果在刷取过程中单独加个铭徽判断我怕误点错了跑到其他格子去了，我到现在为止都只遇见过一次集齐四铭徽。
不过这里商店的集齐四铭徽可以处理不怕点错，下个版本修复，加个判断就行。

**Comment by UCPr251** [comment]
只存银行可以实现，下个版本我就做吧。

**Comment by UCPr251** [comment]
上述已实现：[v1.7.0](https://gitee.com/UCPr251/zzzAuto/releases/tag/v1.7.0)
