### ISSUE TITLE
问题：因点了“开局给鸣徽”导致出现BUG

### ISSUE THREAD

**Issue by Limpdip** [UCPr251/zzzAuto#11]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[Gitee](https://gitee.com/UCPr251/zzzAuto/issues) [Github](https://github.com/UCPr251/zzzAuto/issues)并未发现相关说明

### 你所遇见的问题

如第一张图，添加了该作战机略后，开局会给鸣徽，因此出现BUG
望大哥修复，小弟不胜感激 QAQ
![8fdd750ec82863741a6552d12b07a739](https://github.com/user-attachments/assets/332bc3cb-361b-4b16-a7be-6b5a6db76e89)
![274b64060ca1d96e9f02a1cdbee81076](https://github.com/user-attachments/assets/9181dca0-633d-499a-89dc-ce4d7a064a85)

![7476d2e240eb84ddc96a1b415d247113](https://github.com/user-attachments/assets/7b11d89b-ac94-46d6-a3b0-02729f969f4f)

### 出现频率

每次出现

### 录屏链接

如图所示

### 使用的版本

v1.8.0

### 控制面板截图

![a7692451093fd80411360e7afcdb5a28](https://github.com/user-attachments/assets/9c295936-4dca-4f50-bb21-93a0b60dd41c)

### 其他说明

无

**Comment by Limpdip** [comment]
我上周用了没问题，但是刚刚加了这个作战机略，才出现的问题

**Comment by UCPr251** [comment]
这个我是处理了的，可能是1.8我改了动画等待逻辑才出的问题
我还没点这个，你可以先退回到1.7.1试试看

**Comment by UCPr251** [comment]
你可以录个屏，我看看这里要多久等待时长才好

**Comment by Limpdip** [comment]
ok

**Comment by Limpdip** [comment]
很神奇，突然出现了新的BUG，有可能得让你上我号调试了
问题1：https://www.bilibili.com/video/BV1TVWDe6EkJ/?spm_id_from=333.788.top_right_bar_window_dynamic.content.click&vd_source=fd27eb21a86b39484bfb8cb414ceefda
问题2：https://www.[bilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0](https://www.bilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0)

**Comment by Limpdip** [comment]
> 这个我是处理了的，可能是1.8我改了动画等待逻辑才出的问题 我还没点这个，你可以先退回到1.7.1试试看

OK我试试

**Comment by UCPr251** [comment]
> 很神奇，突然出现了新的BUG，有可能得让你上我号调试了 问题1：https://www.bilibili.com/video/BV1TVWDe6EkJ/?spm_id_from=333.788.top_right_bar_window_dynamic.content.click&vd_source=fd27eb21a86b39484bfb8cb414ceefda 问题2：[https://www.[bilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0](https://www.bilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0)](https://www.%5Bbilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0%5D(https://www.bilibili.com/video/BV1MGWDe3ErA/?spm_id_from=333.999.0.0))

休眠系数太小了，改成1再试试

**Comment by Limpdip** [comment]
OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点

**Comment by UCPr251** [comment]
> OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点

1.8.0呢

**Comment by Limpdip** [comment]
> > OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点
> 
> 1.8.0呢

也测试了，没问题

**Comment by Limpdip** [comment]
> > OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点
> 
> 1.8.0呢

主要就是休眠系数确实不得改

**Comment by UCPr251** [comment]
> > > OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点
> > 
> > 
> > 1.8.0呢
> 
> 主要就是休眠系数确实不得改

这个主要是拿来延长的，减小也压缩不了多少时间的还容易报错

**Comment by UCPr251** [comment]
> > OK，休眠系数改了后1.7.1没问题了，不过如果不会出现BUG的话，我建议作者加个：自动点左上角二倍速，让游戏进行快点
> 
> 1.8.0呢

二倍速这个，你设置里打开记录棋盘加速状态，开一次不就行了，单独加逻辑的话还要全部比例都再取一次坐标，没有必要
