### ISSUE TITLE
问题：大佬，1.2更新了，S级机关门逻辑改了，现在无法通过了

### ISSUE THREAD

**Issue by Gaoxiang2002** [UCPr251/zzzAuto#12]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[Gitee](https://gitee.com/UCPr251/zzzAuto/issues) [Github](https://github.com/UCPr251/zzzAuto/issues)并未发现相关说明

### 你所遇见的问题

大佬，1.2更新了，S级机关门逻辑改了，现在无法通过了

### 出现频率

每次出现

### 录屏链接

略

### 使用的版本

v1.8.2

### 控制面板截图

![image](https://github.com/user-attachments/assets/5a825936-479b-4148-9349-00fc2b6a4071)

**Comment by UCPr251** [comment]
待会儿我看看

**Comment by UCPr251** [comment]
已修复 62de91bd56aaa90386564596fac09291c4e40cfa

**Comment by Gaoxiang2002** [comment]
**太有实力了大佬，这么快就修复了，感谢感谢**❤️
