### ISSUE TITLE
问题：想咨询一个问题，为什么我的 ahk 脚本在绝区零中无效呢

### ISSUE THREAD

**Issue by Beau-xu** [UCPr251/zzzAuto#13]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[Gitee](https://gitee.com/UCPr251/zzzAuto/issues) [Github](https://github.com/UCPr251/zzzAuto/issues)并未发现相关说明

### 你所遇见的问题

按下 xbox A 键时自动发送 A 键，很简单的脚本。在游戏外能触发，但在游戏内按下后没有反应，脚本日志显示没捕捉到按键按下。
```
Joy1::
{
    Send ("{Joy1 down}")   ; Press the Joy1bar down.
    SetTimer(WaitForJoy2, 30)  ; Reduce the number 30 to 20 or 10 to send keys faster. Increase it to send slower.
}

WaitForJoy2()
{
    if not GetKeyState("Joy1")  ; The button has been released.
    {
        Send ("{Joy1 up}")  ; Release the Joy1bar.
        SetTimer(WaitForJoy2, 0)  ; Stop monitoring the button.
        return
    }
    ; Since above didn't "return", the button is still being held down.
    Send ("{Joy1 down}")  ; Send another Joy1bar keystroke.
}
```

### 出现频率

仅此一次

### 录屏链接

*

### 使用的版本

*

### 控制面板截图

*

**Comment by UCPr251** [comment]
游戏内想要运行脚本一般都需要管理员权限，是不是没有以管理员方式打开？
