### ISSUE TITLE
可不可以加入避免电脑关闭屏幕的功能，虽然可以在控制面板改，但是用完脚本还要改回来，有点麻烦，大佬看看能不能加上，如果能实现刷完之前阻止闭屏，刷完之后又不阻止闭屏就更好了

### ISSUE THREAD

**Issue by Gaoxiang2002** [UCPr251/zzzAuto#3]

**Comment by UCPr251** [comment]
为什么在有键鼠输入的情况下还会自动休眠，从没遇见过

**Comment by Gaoxiang2002** [comment]
> 为什么在有键鼠输入的情况下还会自动休眠，从没遇见过

哦，你这么一说好像有道理，我当时是挂了一段时间，回来发现屏幕关闭了，我打来发现一个弹窗，说的是没有匹配到对象之类的报错，我当时就以为是屏幕关闭了，导致了无法识别到对象，你这一说我大概明白了，可能是出了个什么状况，导致了无法识别对象，然后就卡在那了，就没有鼠标和键盘的输入，导致了息屏，看来是我因果搞反了，不好意思，我都快被自己逗笑了，最后还是感谢大佬写了这个自动程序，太感谢了❤️！
