### ISSUE TITLE
问题：全屏是硬性条件还是只要大于1920*1080就可以

### ISSUE THREAD

**Issue by NOWorEVER** [UCPr251/zzzAuto#5]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[gitee](https://gitee.com/UCPr251/zzzAuto/issues) [github](https://github.com/UCPr251/zzzAuto/issues)并未发现相同问题

### 你所遇见的问题？

全屏是硬性条件还是只要大于1920*1080就可以

### 出现频率

仅此一次

### 使用的版本？

v1.3.1

### 屏幕的分辨率？

1920*1080

### 是否开启HDR？

否

### 录屏链接

无

**Comment by UCPr251** [comment]
硬性要求，压根儿没写窗口模式
这个问题你试试不就知道了
