### ISSUE TITLE
零号空洞联系代理人问题

### ISSUE THREAD

**Issue by XiaoMian2** [UCPr251/zzzAuto#6]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[gitee](https://gitee.com/UCPr251/zzzAuto/issues) [github](https://github.com/UCPr251/zzzAuto/issues)并未发现相同问题

### 你所遇见的问题？

在流程“拒绝好意后”，地图上出现联系代理人类型地图时稳定触发，在选择不需要时，多出来一个选择3种类型的鸣徽界面，可能是因为这次1.1版本更新的原因？
![D98A7661472ED3530D1D42AD2B597193](https://github.com/user-attachments/assets/20ff02ae-be16-4e67-b067-16c8650ff85f)

### 出现频率

每次出现

### 使用的版本？

v1.3.1

### 屏幕的分辨率？

1920*1080

### 是否开启HDR？

是

### 联系方式？

769763549

### 录屏链接

https://wwqz.lanzouw.com/iRpIA27g09yj

**Comment by UCPr251** [comment]
gitee已经有人和我说过了，脚本下个版本会修改下框架，到时候会一起处理的

**Comment by XiaoMian2** [comment]
好的，感谢

**Comment by UCPr251** [comment]
脚本已适配游戏1.1版本：[autoZZZv1.4.0](https://github.com/UCPr251/zzzAuto/releases/tag/v1.4.0)
