### ISSUE TITLE
问题：

### ISSUE THREAD

**Issue by SweetflowerMilk** [UCPr251/zzzAuto#7]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[gitee](https://gitee.com/UCPr251/zzzAuto/issues) [github](https://github.com/UCPr251/zzzAuto/issues)并未发现相同问题

### 你所遇见的问题？

在 作战机略 中激活 授权`鸣徽志愿 后, 开局会提供一个鸣徽, 导致后续识别异常

### 出现频率

经常出现

### 录屏链接

1

### 使用的版本？

v1.4

### 屏幕的分辨率？

1920*1080

### 是否开启HDR？

否

**Comment by UCPr251** [comment]
什么问题？说清楚
如果是拒绝好意那里没拒绝到的话，[Gitee](https://gitee.com/UCPr251/zzzAuto/issues/IAKBXH)已经有人和我说了，下个版本修复

**Comment by UCPr251** [comment]
请尝试最新版[v1.5.0](https://github.com/UCPr251/zzzAuto/releases/tag/v1.5.0)
