### ISSUE TITLE
问题：商店

### ISSUE THREAD

**Issue by EmpCCC** [UCPr251/zzzAuto#8]
### 这个问题是否已有说明？

- [X] 我已查看[注意事项](https://gitee.com/UCPr251/zzzAuto#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)及现有issues：[Gitee](https://gitee.com/UCPr251/zzzAuto/issues) [Github](https://github.com/UCPr251/zzzAuto/issues)并未发现相同问题

### 你所遇见的问题？

在某些情况下选择的门口的盗洞客提供的支援是随机刷新一个商店，如果在脚本路径上会导致报错地图类型识别异常。
![QQ20240818-204709](https://github.com/user-attachments/assets/2fc57e5a-2c36-43b5-987b-396197132919)
![QQ20240818-231504](https://github.com/user-attachments/assets/80ad3434-e8a7-43d7-b619-b9b5b9b33336)

### 出现频率

经常出现

### 录屏链接

1

### 使用的版本？

v1.5.3

### 屏幕的分辨率？

1920*1080

### 是否开启HDR？

否

**Comment by UCPr251** [comment]
开HDR啥的没，正常根本不会选择这个选项的，如果脚本误点了，你可以在控制面板把颜色搜索允许渐变值改小一点再试试。我测试的数百次里没有一次误点过商店

**Comment by EmpCCC** [comment]
> 开HDR啥的没，正常根本不会选择这个选项的，如果脚本误点了，你可以在控制面板把颜色搜索允许渐变值改小一点再试试。我测试的数百次里没有一次误点过商店

没有开hdr。在关闭自定义缩放(100%)调整为100%选项，重装显卡驱动，颜色搜索允许60后就没有复现过了😅，算是解决了
