### ISSUE TITLE
希望可以在窗口模式运行

### ISSUE THREAD

**Issue by suixinex** [UCPr251/zzzAuto#9]
这样在运行时也能看看视频看看直播之类的

**Comment by UCPr251** [comment]
[用这个](https://github.com/sMythicalBird/ZenlessZoneZero-Auto)

**Comment by suixinex** [comment]
> [用这个](https://github.com/sMythicalBird/ZenlessZoneZero-Auto)

这也……太大了😂😂包含全套的多个OCR和图像识别模型，有种……杀鸡焉用牛刀的感觉，还有点特别臃肿，还是autohotkey小巧易用精简

**Comment by UCPr251** [comment]
我这脚本的设计初衷也是简单轻量，让不同分辨率、HDR、字体粗细等都能自适应不用来回调整。一般刷这个业绩睡前打开，开启刷完自动关闭游戏，睡醒就完事儿了。
适配窗口的话，要考虑缩放的问题，标题栏等等，原本的框架也要改很多，坐标数据也要全部试一下校准。
图像识别模拟键鼠输入的话，刷取期间也只能干瞪眼看着不能干啥的，窗口模式看视频不能全屏也不爽，反正一周2、3h就刷完了，适配窗口感觉费力不讨好，暂时没有这方面的打算。
后续如果有闲暇的话我可能会试试，不过别抱太大希望，近期应该是不会弄的。
感谢支持。

**Comment by suixinex** [comment]
> 我这脚本的设计初衷也是简单轻量，让不同分辨率、HDR、字体粗细等都能自适应不用来回调整。一般刷这个业绩睡前打开，开启刷完自动关闭游戏，睡醒就完事儿了。 适配窗口的话，要考虑缩放的问题，标题栏等等，原本的框架也要改很多，坐标数据也要全部试一下校准。 图像识别模拟键鼠输入的话，刷取期间也只能干瞪眼看着不能干啥的，窗口模式看视频不能全屏也不爽，反正一周2、3h就刷完了，适配窗口感觉费力不讨好，暂时没有这方面的打算。 后续如果有闲暇的话我可能会试试，不过别抱太大希望，近期应该是不会弄的。 感谢支持。

好的，也可能仅仅是个人小众需求，目前也很好用，感谢大佬制作分享~

**Comment by UCPr251** [comment]
已支持窗口模式，欢迎尝试

**Comment by suixinex** [comment]
> 已支持窗口模式，欢迎尝试

测试运行正常，感谢适配~

**Comment by UCPr251** [comment]
> > 已支持窗口模式，欢迎尝试
> 
> 测试运行正常，感谢适配~

OK
